### ISSUE TITLE
It looks like setting gSeed sets the seed for the entire length of the R session

### ISSUE THREAD

**Issue by jeffdumont** [RSGInc/RSGHB#55]
I would expect that setting the seed would only affect the HB estimation and not subsequent random draws outside of RSGHB (ie. randomly selecting observations for cross-validation).

After doHB has completed, it should reset the random number generator to its previous state.

**Comment by jeffkeller87** [comment]
I was thinking about this recently – should there even be a gSeed parameter? I can’t think of any other model functions that do this, users are expected to set their seeds outside of the function.

What would the expected behavior be for the following pseudo-code? Would it be confusing to users?

# user sets their own seed
set.seed(1)

# some other stochastic calculations
runif(1)

# RSGHB is used
doHB(…, gSeed = 1234)
# doHB resets seed, but to what? The current random state via .Random.seed?

# follow up stochastic calculations
runif(1)

**Comment by jeffdumont** [comment]
Let's talk about this. I want to make sure that models are repeatable which means storing a seed somewhere in the model object. I wouldn't expect the model seed to affect other random number generation outside of the model estimation.

**Comment by jeffkeller87** [comment]
I agree, but the current method does affect random number generation post-doHB call (code block 1). The presence of the gSeed argument implicitly suggests that x1 should equal x2. One alternative is to let users control the random seed outside of the doHB function (code block 2). This is how most model functions behave. Another alternative is to store a snapshot of the random seed at the start of the doHB call via .Random.Seed and restore it at the end of the doHB call (like how many plot functions restore plotting options).


### Code block 1
# A faux doHB function
doHB <- function(gSeed) {

  set.seed(gSeed)
  runif(100)

}


# Test without doHB
set.seed(1987)
x1 <- runif(1)


# Test with doHB in between
set.seed(1987)
temp <- doHB(gSeed = 1)
x2 <- runif(1)

identical(x1, x2)
x1
x2

### Code block 2
doHB <- function() {

  runif(100)

}


# run a "model"
set.seed(1987)
model1 <- doHB()


# model is still repeatable
set.seed(1987)
model2 <- doHB()

identical(model1, model2)

**Comment by jeffdumont** [comment]
Your alternative is what I was thinking how it would work.

**Comment by jeffkeller87** [comment]
Which alternative? (There were two)

**Comment by jeffdumont** [comment]
This one

"Another alternative is to store a snapshot of the random seed at the start of the doHB call via .Random.Seed and restore it at the end of the doHB call (like how many plot functions restore plotting options)."

**Comment by jeffkeller87** [comment]
So, in order to do this, we need to be able to modify the .Random.seed variable in the global environment via "rng.state  ->> .Random.seed" or "assign('.Random.seed', value = rng.state, envir = .GlobalEnv)", where "rng.state" is the random number state that we want to restore.

Jeff, wasn't this something that CRAN will not allow packages to do? (That is, modifying the global environment.) I recall you having to make some changes along these lines to the very first version of RSGHB that made it onto CRAN. If that's the case, then I think we'll have to abandon this feature.

**Comment by jeffdumont** [comment]
Yes. That is not allowed.

In this case, I agree that we should abandon this feature and we should
require the user to set the random seed outside of RSGHB. So it wouldn't be
a parameter passed into the control list.

**Comment by jeffkeller87** [comment]
gSeed has been deprecated. Users should use set.seed() directly outside of doHB calls.
